### ISSUE TITLE
Observer Implementation

### ISSUE THREAD

**Issue by coriumalpha** [tomidix/CSharpTradFriLibrary#13]
Hi tomidix,

I've seen in other Tradfri related libraries that they're using CoAP's Observe ([CoAP Observe](https://github.com/Com-AugustCellars/CoAP-CSharp/tree/master/CoAP.NET/Observe)) functionality, after some simple and fast testing, I'd begin developing some Observe based controllers for the existing Get methods and they work properly.

I'd be glad to know if you're currently developing these methods (or going to in near future) yourself or if you will be interested in a pull request from mine with that implementation. Just let me know, because I think it will be interesting to have access to thoose controller methods and to be able to access the status of the devices without polling recursively. Thank you for your time.

**Comment by p3root** [comment]
I have interested in those functions. Could you open a pull request anyway, so that others see what you did?

**Comment by coriumalpha** [comment]
Just lemme two days or so for cleaning up the code a bit and I'll be glad to open the pull request

**Comment by tomidix** [comment]
PR approved and completed. This is now available
