### ISSUE TITLE
[request] implement wrapper for setting CIE Yxy colors

### ISSUE THREAD

**Issue by juliusdeblaaij** [tomidix/CSharpTradFriLibrary#25]
I have made use of the preset Tradfri colors in the library. However when I wanted to create custom colors by setting the value in coap 5709 and 5710 there really weren't any function available.
Perhaps someone could take a crack at implementing it, as I find great use in the library!
Some material to explain what CIE colors are:
Info on the colors:
https://github.com/ffleurey/ThingML-Tradfri

If anyone needs additional info, I can hopefully supply it.

"implementation requirements"
- The ability to put values between 0 and 65535 into 5709 (x color) and 5710 (y color)
- (Optional) color conversion from say RGB to CIE Yxy colors to put into x color and y color

**Comment by tomidix** [comment]
I've implemented the wrapper using the exact same algorithm for conversion as they've used in linked application. I need someone with color bulbs to test it. The Variable Temperature Bulbs which I have always sets some warm color no matter the color chosen.

Tradfri UI which supports this is here: [feature/#25-color-wrapper](https://github.com/tomidix/CSharpTradFriLibrary/tree/feature/%2325-color-wrapper)

**Comment by dominikjancik** [comment]
I have tested and fixed the library code that deals with setting X and Y values in the bulbs. See the [pull request](https://github.com/tomidix/CSharpTradFriLibrary/pull/38)

**Comment by tomidix** [comment]
This one is now available. Thanks @dominikjancik for testing and fixes.
