### ISSUE TITLE
No devices returned by GetDeviceObjects, stalls application

### ISSUE THREAD

**Issue by juliusdeblaaij** [tomidix/CSharpTradFriLibrary#26]
Everything worked fine up until some days ago when GetDeviceObjects started to "break" my application. I added the source code to my project so I could debug the code, I've found that inside GatewayController the GetEntityCollectionIDs task doesn't return anything and silently stalls my application. Therefore GetDeviceObjects doesn't even hit its return statement.
If anyone could look into this that would be great.
Since this is quite a breaking issue I've taken it upon me to mention you
@tomidix

**Comment by tomidix** [comment]
@juliusdeblaaij can you provide your gateway version? 
Latest tested version is: 1.8.25.

**Comment by juliusdeblaaij** [comment]
Thank you for your reply. My current version is 1.8.0026. It might be good to know the testing thus isn't fully up to date. 
I found out through my IP scanning software that my Hub has changed it's IP address. I fixed this in my code and all seems to be working. I will now close the issue.
