### ISSUE TITLE
C# use without UI

### ISSUE THREAD

**Issue by Hydro8** [tomidix/CSharpTradFriLibrary#3]
Hi
How do you use your library without GUI ? For example, I guess there is a function to connect to the gateway.

Since Ikea change the way to connect to the gateway, I can't connect anymore wth my own C# code :(

**Comment by tomidix** [comment]
Just use the UI project **as an example**. Clone the repo, start the solution and go through the main.cs code step by step. You should get an idea how to use the library. More-less everything is the same if you don't use windows forms (gui) except you won't use the windows forms specific objects like datagridview for showing the devices and buttons to trigger events. You should then use your own way to handle those.
