### ISSUE TITLE
[Feature] - documentation

### ISSUE THREAD

**Issue by bendelathouwer** [tomidix/CSharpTradFriLibrary#35]
Dear 

Is it posible to use some documentation ?
For example a simple blinky?

With best regards Ben

**Comment by tomidix** [comment]
Can you please elaborate more specifically what do you want?

**Comment by bendelathouwer** [comment]
simple blinky and writen documentation explaining the core function calls in depth if that's a possibility

**Comment by tomidix** [comment]
What is "blinky" and what's it's purpose? You already have an example project in repository.
Take [SetSelectedLights](https://github.com/tomidix/CSharpTradFriLibrary/blob/master/TradfriUI/Main.cs) function and use it with Timer object to make blinking effect..

What exact functions do you need explanation for? The names of the functions are more or less self-explaining so I do not see a need for writing documentation for functions like SetColor, SetDimmer, SetLight, SetOutlet.. If you are using editor with intellisense it should be even more clear to you what you are doing..
