### ISSUE TITLE
[BUG] - GenerateAppSecret timeout

### ISSUE THREAD

**Issue by JKorf** [tomidix/CSharpTradFriLibrary#36]
Thanks for your work! I think I've encountered a bug:

**Describe the bug**
Calling GenerateAppSecret when the hub is not available takes 145 seconds to complete, after which it throws a nullreference exception.

**To Reproduce**
1. call GenerateAppSecret when the hub is not online.
2. wait

**Expected behavior**
Throw some sort of descriptive error. Also the timeout should be configurable.

**Comment by tomidix** [comment]
Hi,

I've reduced timeout to 10s and added a custom exception for timeout. For now I don't have time to implement configurable timeouts and exception for every call.
Feel free to contribute if you have time. From current perspective I would call that a feature, not a bug so I consider this one as solved.
