### ISSUE TITLE
New GW-Firmware with new Authentication

### ISSUE THREAD

**Issue by marioqx** [tomidix/CSharpTradFriLibrary#9]
tomidix,

first I would like to thank you for the cool library. I'm about to create a disco-light using NAudio and your tradfri-library.

While doing so I cam acrosse the following:
https://github.com/home-assistant/home-assistant/issues/10252

IKEA apparently changed authentication in order not to require to save the GW-key in every app for apparent security reasons.

Instead, the introduce a connection oriented authentication with a connection-name and connection-key. This pair needs to be once obtained with the use of the GW-key.

Could you please adapt your library accordingly. 

Thanks
Marioqx

**Comment by tomidix** [comment]
Thanks for the info, I'll look at it as soon as I find some time.

**Comment by marioqx** [comment]
Thanks for picking this up. I've created a repository with one application building on your library in return. I do have some further suggested changes/commits to your library if desired.

**Comment by tomidix** [comment]
I've added you as a collaborator, you should be able to fork the repo and make pull requests if you have any suggestions.. feel free to do it

**Comment by tomidix** [comment]
this is solved in v0.3.0.18
